before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: FjVI2/Mk1pSUCGkRK6Xu4zRaXDQ0tcwOCW4jkAEPekgjKP7kmRS8lMNZg7ycDmIdMJVacBos+I++aYpY1u+eIPPJKs/MiCFPJTZKcD2CVWJ55hjEUpzYnpsmzl4l9OHschnTTIBpcOXKVqlLERVtylHj+65qn+zaUheSFXBeiRfOh1vYgZakF2L9FRhtsQB4ZR75fwtaGEGfhDcltDeecgp7+f/gZLR+ekmIZgTGNzGc5PinK+SXHf0OHlmmd+yKeBdOWHTDdFM0axkGAqeu+tqUvyfJ7u8wyItRqytyBu69RHrjc3z1/AuqKZ8dGttw9HwIs1CT8fExgLjbeMeB7vPskG76qGmFlI2X4wc8LNqp1Pl4Blk9IC+uDWoR9Yy41QYgeS0eJdppS027qAonlM7ehjQdicOSJrv4cirhFhkMBOOEFGu7kSHTDZonc6ORV+UodXo+EiY8LzR/Cb8PRMiFOAKpCV/PgiNxbKW40KIflysvLhVhvnp9nUnezkNtLF2CKdHl2LeLHdI4FymdLbET/aMzPSKL8KWZ5DS1X8RWRtjWmBexiK+J21N6FPggvKjhzN+Kvz7PFxmRga/Ku11EjJKeMo17ecqbAYzvrBj6TG25zf7lAI6Vr31rnajugmVR/FSnqn9XSCSBN3gwhpNsmGUTWPu5++0fKvmWjvo= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
